config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  
  resources :providers do
    get "providers_report", :on => :collection
    get "account_report", :on => :collection   
  end
  
  resources :products do
    get "product_list_report", :on => :collection
  end
  
  resources :clients do
    get "clients_report", :on => :collection
    get "account_report", :on => :collection   
  end
  
  resources :documents do
    get "documents_report", :on => :collection
    get "document_report", :on => :collection
    get "document_report2", :on => :collection
    get "document_report3", :on => :collection
    get "personalize_report", :on => :collection
  end
  
  resources :users
  resources :companies
  resources :clients
  resources :providers
  resources :warehouses
  resources :products
  resources :brands
  resources :categories
  resources :documents
  resources :document_types
  resources :document_lines
  resources :stocks
  resources :payments
  resources :payments_documents
  resources :payment_types
  
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do

    devise_for :users, :controllers => { :registrations => "registrations"}
    
    get '/:locale/documents/search' => 'documents#search', :as => :documents_search
    get '/:locale/stocks/search' => 'stocks#search', :as => :stock_search
    get '/:locale/clients/search' => 'clients#search', :as => :client_search
    get '/:locale/providers/search' => 'providers#search', :as => :provider_search
    get '/:locale/products/search' => 'products#search', :as => :products_search
    get '/:locale/payments_documents/search' => 'payments_documents#search', :as => :payments_documents_search

    get '/:locale/companies/settings' => 'companies#settings', :as => :settings
    get '/:locale/companies/edit_formats' => 'companies#edit_formats', :as => :edit_formats     
 
    get '/:locale/clients/autocomplete' => 'clients#autocomplete', :as => :client_autocomplete
    get '/:locale/clients/get_info_account' => 'clients#get_info_from_selected_account', :as => :get_info_client

    get '/:locale/providers/autocomplete' => 'providers#autocomplete', :as => :provider_autocomplete
    get '/:locale/providers/get_info_account' => 'providers#get_info_from_selected_account', :as => :get_info_provider

    get '/:locale/warehouses/autocomplete' => 'warehouses#autocomplete', :as => :warehouse_autocomplete
    get '/:locale/warehouses/get_info_account' => 'warehouses#get_info_from_selected_account', :as => :get_info_warehouse   

    delete '/:locale/documents/remove_document_line' => 'documents#remove_document_line', :as => :document_remove_document_line
    post '/:locale/documents/create_document_line' => 'documents#create_document_line', :as => :create_document_line
    get '/:locale/documents/create_document_account' => 'documents#create_document_account', :as => :create_document_account  
    get '/:locale/documents/new' => 'documents#new', :as => :new

    get '/:locale/products/autocomplete' => 'products#autocomplete', :as => :product_autocomplete
    get '/:locale/products/get_info_product' => 'products#get_info_from_selected_product', :as => :get_info_product

    get '/:locale/payments_documents/add_payments_document_id' => 'payments_documents#add_payments_document_id', :as => :add_payments_document_id  
    get '/:locale/payments_documents/remove_payments_document_id' => 'payments_documents#remove_payments_document_id', :as => :remove_payments_document_id  
    post '/:locale/payments_documents/create_payment_line' => 'payments_documents#create_payment_line', :as => :create_payment_line
#    get '/:locale/payments_documents/new' => 'payments_documents#new', :as => :new
    get '/:locale/payments_documents/new_modal' => 'payments_documents#new_modal', :as => :new_modal
    get '/:locale/payments_documents/create_payments_document_account' => 'payments_documents#create_payments_document_account', :as => :create_payments_document_account   

    get '/:locale/learn' => 'learn#index', :as => :learn_personalize_report
    get '/:locale/privacy' => 'privacy#index', :as => :privacy
    get '/:locale/terms' => 'terms#index', :as => :terms 

    patch '/upload_logo' => 'companies#upload_logo', :as => :upload_logo
    get '/delete_logo' => 'companies#delete_logo', :as => :delete_logo
    
    get '/:locale/service_payments/subscribe_month' => 'service_payments#subscribe_month', :as => :subscribe_month 
    get '/:locale/service_payments/subscribe_year' => 'service_payments#subscribe_year', :as => :subscribe_year
  end
end

app/models/user.rb
class User < ApplicationRecord
  self.primary_key = 'id'   
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  rolify
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :company, :foreign_key => 'domain'       

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource

  def index
   # authorize! :index, @user, :message => 'Not authorized as an administrator.'
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user], :as => :admin)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end
    
  def destroy
    user = User.find(params[:id])
    unless user == current_user
      user.destroy
      redirect_to users_path, :notice => "User deleted."
    else
      redirect_to users_path, :notice => "Can't delete yourself."
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_edit.html.erb
<div class="modal-header">
<h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'] %></h1>
</div>
<%= render "remote-form" %>

app/views/users/_form.html.erb
<%= simple_form_for @user, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :email %>
  <%= f.input :name %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                users_path, :class => 'btn' %>
  </div>
<% end %>

app/views/users/_remote-form.html.erb
<%= simple_form_for(@user, :url => registration_path(@user), :html => { :method => :put, :class => 'form-vertical' }) do |f| %>
<div class="modal-body" >
  <ul class="errors"></ul>
  <%= f.error_notification %>
  <%= display_base_errors @user %>
  <%= f.input :name, :autofocus => true %>
  <%= f.input :email, :required => true %>
  <%= f.input :password, :autocomplete => "off", :hint => "leave it blank if you don't want to change it", :required => false %>
  <%= f.input :password_confirmation, :required => false %>
  <%= f.input :current_password, :hint => "we need your current password to confirm your changes", :required => true %>
  <div class="form-actions">
    <%= f.button :submit, 'Update', :class => 'btn-primary' %>
    <%= submit_tag 'Cancel', :type => :reset, :class => "btn btn-danger", "data-dismiss" => "modal", "aria-hidden" => "true" %>
  </div>
</div>
<% end %>

app/views/users/_user.html.erb
<div id="role-options-<%= user.id %>" class="modal" style="display: none;">
  <%= simple_form_for user, :url => user_path(user), :html => {:method => :put, :class => 'form-horizontal' } do |f| %>
    <div class="modal-header">
      <a class="close" data-dismiss="modal">&#215;</a>
      <h3>Change Role</h3>
    </div>
    <div class="modal-body">
      <%= f.input :role_ids, :collection => Role.all, :as => :radio_buttons, :label_method => lambda {|t| t.name.titleize}, :label => false, :item_wrapper_class => 'inline', checked: user.role_ids.first %>
    </div>
    <div class="modal-footer">
      <%= f.submit "Change Role", :class => "btn" %>
      <a class="btn" data-dismiss="modal" href="#">Close</a>
    </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/users/index.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:company_name) %></th>
      <th><%= model_class.human_attribute_name(:domain) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.id, user_path(user) %></td>
        <td><%= user.email %></td>
        <td><%= user.name %></td>
        <td><%= user.company_name %></td>
        <td><%= user.domain %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_user_path(user), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      user_path(user),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_user_path,
            :class => 'btn btn-primary' %>

app/views/users/new.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/users/show.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @user.email %></dd>
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @user.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:company_name) %>:</strong></dt>
  <dd><%= @user.company_name %></dd>

</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              users_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_user_path(@user), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              user_path(@user),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>