config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  
  resources :providers do
    get "providers_report", :on => :collection
    get "account_report", :on => :collection   
  end
  
  resources :products do
    get "product_list_report", :on => :collection
  end
  
  resources :clients do
    get "clients_report", :on => :collection
    get "account_report", :on => :collection   
  end
  
  resources :documents do
    get "documents_report", :on => :collection
    get "document_report", :on => :collection
    get "document_report2", :on => :collection
    get "document_report3", :on => :collection
    get "personalize_report", :on => :collection
  end
  
  resources :users
  resources :companies
  resources :clients
  resources :providers
  resources :warehouses
  resources :products
  resources :brands
  resources :categories
  resources :documents
  resources :document_types
  resources :document_lines
  resources :stocks
  resources :payments
  resources :payments_documents
  resources :payment_types
  
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do

    devise_for :users, :controllers => { :registrations => "registrations"}
    
    get '/:locale/documents/search' => 'documents#search', :as => :documents_search
    get '/:locale/stocks/search' => 'stocks#search', :as => :stock_search
    get '/:locale/clients/search' => 'clients#search', :as => :client_search
    get '/:locale/providers/search' => 'providers#search', :as => :provider_search
    get '/:locale/products/search' => 'products#search', :as => :products_search
    get '/:locale/payments_documents/search' => 'payments_documents#search', :as => :payments_documents_search

    get '/:locale/companies/settings' => 'companies#settings', :as => :settings
    get '/:locale/companies/edit_formats' => 'companies#edit_formats', :as => :edit_formats     
 
    get '/:locale/clients/autocomplete' => 'clients#autocomplete', :as => :client_autocomplete
    get '/:locale/clients/get_info_account' => 'clients#get_info_from_selected_account', :as => :get_info_client

    get '/:locale/providers/autocomplete' => 'providers#autocomplete', :as => :provider_autocomplete
    get '/:locale/providers/get_info_account' => 'providers#get_info_from_selected_account', :as => :get_info_provider

    get '/:locale/warehouses/autocomplete' => 'warehouses#autocomplete', :as => :warehouse_autocomplete
    get '/:locale/warehouses/get_info_account' => 'warehouses#get_info_from_selected_account', :as => :get_info_warehouse   

    delete '/:locale/documents/remove_document_line' => 'documents#remove_document_line', :as => :document_remove_document_line
    post '/:locale/documents/create_document_line' => 'documents#create_document_line', :as => :create_document_line
    get '/:locale/documents/create_document_account' => 'documents#create_document_account', :as => :create_document_account  
    get '/:locale/documents/new' => 'documents#new', :as => :new

    get '/:locale/products/autocomplete' => 'products#autocomplete', :as => :product_autocomplete
    get '/:locale/products/get_info_product' => 'products#get_info_from_selected_product', :as => :get_info_product

    get '/:locale/payments_documents/add_payments_document_id' => 'payments_documents#add_payments_document_id', :as => :add_payments_document_id  
    get '/:locale/payments_documents/remove_payments_document_id' => 'payments_documents#remove_payments_document_id', :as => :remove_payments_document_id  
    post '/:locale/payments_documents/create_payment_line' => 'payments_documents#create_payment_line', :as => :create_payment_line
#    get '/:locale/payments_documents/new' => 'payments_documents#new', :as => :new
    get '/:locale/payments_documents/new_modal' => 'payments_documents#new_modal', :as => :new_modal
    get '/:locale/payments_documents/create_payments_document_account' => 'payments_documents#create_payments_document_account', :as => :create_payments_document_account   

    get '/:locale/learn' => 'learn#index', :as => :learn_personalize_report
    get '/:locale/privacy' => 'privacy#index', :as => :privacy
    get '/:locale/terms' => 'terms#index', :as => :terms 

    patch '/upload_logo' => 'companies#upload_logo', :as => :upload_logo
    get '/delete_logo' => 'companies#delete_logo', :as => :delete_logo
    
    get '/:locale/service_payments/subscribe_month' => 'service_payments#subscribe_month', :as => :subscribe_month 
    get '/:locale/service_payments/subscribe_year' => 'service_payments#subscribe_year', :as => :subscribe_year
  end
end

app/models/document.rb
class Document < ApplicationRecord
  self.primary_key = 'id'  
  self.inheritance_column = nil

  belongs_to :company, :foreign_key => 'domain'
  belongs_to :document_type
  belongs_to :account
  belongs_to :warehouse
  belongs_to :payments_document

  has_many :document_lines, :foreign_key => 'header_id'

  before_validation :ensure_counter_is_not_greater_than_limit, :on => :create
  before_create :increment_counter, :default_values 
  before_save :save_type_description, :save_child_type 
  
  def default_values
      self.status ||= 'NOT_PAID'
  end

  def save_type_description
    self.type = self.document_type.description
  end

  def save_child_type
    Document.transaction do
      document_lines.each do |child|
        child.type = self.type 
        child.save
      end
    end
  end

  private
    def ensure_counter_is_not_greater_than_limit
      if self.company.counter >= self.company.limit
        errors[:base] << "Ha alcanzado el limite de su plan. Por favor actualice su plan para seguir usando la aplicacion"
      end
    end

    def increment_counter
      self.company.counter = self.company.counter + 1
      self.company.save
    end


  def full_name
     "#{type} ------ #{document_number} ------- #{account.name} -------- #{date} ---------- #{sub_total}---------- #{tax_total}---------- #{total}"
   end

end

app/models/document_type.rb
class DocumentType < ApplicationRecord
  self.primary_key = 'id'  
  validates :description, presence: true

  belongs_to :company, :foreign_key => 'domain'

  ACCOUNT_TYPES = ["Client","Provider","Warehouse"]
  validates :account_type, inclusion: ACCOUNT_TYPES

  STOCK_TYPES = ["debit","credit"]
  validates :stock_type, inclusion: STOCK_TYPES

end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  # GET /documents
  # GET /documents.json
  before_action :authenticate_user!
  def search
   @start_at = params[:start_at].blank? ? DateTime.parse("01/01/1901") : DateTime.parse(params[:start_at])
   @end_at = params[:end_at].blank? ? DateTime.parse("01/01/2901") : DateTime.parse(params[:end_at])
   @name = params[:name]
   @status = params[:status]
   @type = params[:type]
   if @status.blank?
     if @type.blank?
      @documents = Document.joins(:account).where("documents.domain = ? AND name like ? AND date >= ? AND date <= ? ", current_user.domain,"%#{@name}%","#{@start_at}","#{@end_at}").paginate(:page => params[:page], :per_page => 10).order('date DESC')
     else
      @documents = Document.joins(:account).where("documents.domain = ? AND name like ? AND documents.type = ? AND date >= ? AND date <= ? ", current_user.domain,"%#{@name}%","#{@type}","#{@start_at}","#{@end_at}").paginate(:page => params[:page], :per_page => 10).order('date DESC')
     end
   else
     if @type.blank?
      @documents = Document.joins(:account).joins("LEFT OUTER JOIN payments_documents ON payments_documents.id = documents.payments_document_id").where("documents.domain = ? AND accounts.name like ? AND documents.date >= ? AND documents.date <= ? AND (payments_documents.status = ? OR (documents.status = ? AND payments_documents.id IS NULL))", current_user.domain,"%#{@name}%","#{@start_at}","#{@end_at}","#{@status}","#{@status}").paginate(:page => params[:page], :per_page => 10).order('date DESC')
     else
      @documents = Document.joins(:account).joins("LEFT OUTER JOIN payments_documents ON payments_documents.id = documents.payments_document_id").where("documents.domain = ? AND accounts.name like ? AND documents.type = ? AND documents.date >= ? AND documents.date <= ? AND (payments_documents.status = ? OR (documents.status = ? AND payments_documents.id IS NULL))", current_user.domain,"%#{@name}%","#{@type}","#{@start_at}","#{@end_at}","#{@status}","#{@status}").paginate(:page => params[:page], :per_page => 10).order('date DESC')
     end
   end      
    render :index
  end

 
  def index
    @documents = current_user.company.documents.paginate(:page => params[:page], :per_page => 10).order('date DESC')

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @documents }
      format.js {}
    end
  end

  # GET /documents/1
  # GET /documents/1.json
  def show
    @document = Document.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @document }
    end
  end

  # GET /documents/new
  # GET /documents/new.json
  def new
    @document = Document.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @document }
    end
  end

  # GET /documents/1/edit
  def edit
    @document = Document.find(params[:id])
  end

  # PUT /documents/1
  # PUT /documents/1.json
  def update
    params[:document][:version] = ENV["VERSION"]
    params[:document][:username] = current_user.username
    @document = Document.find(params[:id])

    respond_to do |format|
      if @document.update_attributes(document_params)
        format.html { redirect_to @document, notice: 'Document was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /documents/1
  # DELETE /documents/1.json
  def destroy
    @document = Document.find(params[:id])
    @document.destroy

    respond_to do |format|
      format.html { redirect_to documents_url }
      format.json { head :no_content }
    end
  end

  def is_document_not_paid
    @document = Document.find(params[:id])
    @document.status == "NOT_PAID"
  end
    
  def remove_document_line
    @document_line = DocumentLine.find(params[:id])
    @document_line.destroy

    respond_to do |format|
        format.html { redirect_to @document_line.document, notice: 'Document was successfully updating.' }
        format.json { render json: @document_line.document, status: :created, location: @document }
        format.js
    end
  end

  def create_document_line
    product = Product.find(params[:autocomplete])
    document = Document.find(params[:header_id])
    quantity = params[:quantity].to_f
    price = params[:price].to_f
    total = quantity*price
    document_line = DocumentLine.new(domain: current_user.domain, username: current_user.username,
      code: product.code, date: DateTime.now, description: product.description, document_number: document.document_number,
	    header_id: document.id, product_id: product.id, warehouse_id: document.warehouse.id, 
	    in_quantity:0, out_quantity: quantity,price: price, total: total, type: document.type, month: DateTime.now.month, year: DateTime.now.year)
    if document_line.save!
      flash[:notice]='Your line was created'
    else
      flash[:notice]='Please verify your data'
    end

    respond_to do |format|
      format.html{ redirect_to document }
    end
  end  
  
  def create_document_account
    begin
      account_type = DocumentType.find(params[:document][:document_type_id]).account_type
      puts "esta es " + account_type
      if(account_type=='Client')
          account = Client.find(params[:autocomplete_client])
      elsif(account_type=='Provider')
           account = Provider.find(params[:autocomplete_provider])     
      elsif(account_type=='Warehouse')
           account = Warehouse.find(params[:autocomplete_warehouse])           
      end
    rescue ActiveRecord::RecordNotFound => e
      account = nil
    end

    if account
      create_document(account) 
    else
      @document = Document.new(document_params) 
      params[:document][:type] = params[:document][:document_type_id]
      @document.errors[:base] << t("helpers.labels.not_provider_present") # Not provider
      render :action => :new # Not provider
    end    
  end




    def create_document(account) 


      params[:document][:version] = ENV["VERSION"]
      params[:document][:domain] = current_user.domain
      params[:document][:username] = current_user.username
      params[:document][:account_id] = account.id
      params[:document][:code] = account.code
      params[:document][:discount_percentage] = 0
      params[:document][:discount_total] = 0
      params[:document][:sub_total] = (params[:document][:sub_total].blank? ? 0 : params[:document][:sub_total])
      params[:document][:tax_total] = ((params[:document][:tax].to_f)*(params[:document][:sub_total].to_f)/100).round(2)
      params[:document][:total] = (params[:document][:sub_total].to_f + params[:document][:tax_total].to_f).round(2)
      params[:document][:paid] = 0
      params[:document][:paid_left] = 0    
      params[:document][:month] = Time.new.month+1
      params[:document][:year] = Time.new.year+1900
      params[:document][:status] = "NOT_PAID"
      
    @document = Document.new(document_params)

    respond_to do |format|
      if @document.save
        format.html { redirect_to @document, notice: 'Document was successfully created.' }
        format.json { render json: @document, status: :created, location: @document }
      else
        params[:document][:type] = params[:document][:document_type_id] 
        format.html { render action: "new" }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

 
  def documents_report
    #raise params.inspect
    @user = current_user
    @start_at = params[:start_at].blank? ? DateTime.parse("01/01/1901") : DateTime.parse(params[:start_at])
    @end_at = params[:end_at].blank? ? DateTime.parse("01/01/2901") : DateTime.parse(params[:end_at])
    @name = params[:name]
    @status = params[:status]
    @type = params[:type]
    if @status.blank?
     if @type.blank?
      @documents = Document.joins(:account).where("documents.domain = ? AND name like ? AND date >= ? AND date <= ? ", current_user.domain,"%#{@name}%","#{@start_at}","#{@end_at}")
     else
      @documents = Document.joins(:account).where("documents.domain = ? AND name like ? AND documents.type = ? AND date >= ? AND date <= ? ", current_user.domain,"%#{@name}%","#{@type}","#{@start_at}","#{@end_at}")
     end
    else
     if @type.blank?
      @documents = Document.joins(:account).joins("LEFT OUTER JOIN payments_documents ON payments_documents.id = documents.payments_document_id").where("documents.domain = ? AND accounts.name like ? AND documents.date >= ? AND documents.date <= ? AND (payments_documents.status = ? OR (documents.status = ? AND payments_documents.id IS NULL))", current_user.domain,"%#{@name}%","#{@start_at}","#{@end_at}","#{@status}","#{@status}")
     else
      @documents = Document.joins(:account).joins("LEFT OUTER JOIN payments_documents ON payments_documents.id = documents.payments_document_id").where("documents.domain = ? AND accounts.name like ? AND documents.type = ? AND documents.date >= ? AND documents.date <= ? AND (payments_documents.status = ? OR (documents.status = ? AND payments_documents.id IS NULL))", current_user.domain,"%#{@name}%","#{@type}","#{@start_at}","#{@end_at}","#{@status}","#{@status}")
     end
    end       
    pdf = DocumentsReport.new(@documents, @user, @start_at, @end_at)
    send_data pdf.render, filename:'documents_report.pdf',type: 'application/pdf', disposition: 'inline'
  end
  
  def document_report
      #raise params.inspect
      user = current_user
      @document = Document.find(params[:format])
      pdf = DocumentReport.new(@document, user)

app/views/documents/_account.html.erb
<div class="alert alert-info"><%=@account.name %></div>


app/views/documents/_client.html.erb
<%- model_class = Client -%>
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.js"></script>
<div class="row-fluid">
  <div class="span10">
	<div class="modal fade" id="client-modal"></div>
    <%= form_for @document, :url => {:action => "create_document_account"}, :method => "get"  do |f| %>
      <%= render 'shared/error_messages', :object => @document %>
      <dl class="dl-horizontal">
	    <dt><strong><%=t '.clients', :default =>  t("helpers.labels.clients") %></strong></dt>
	    <dd><%= text_field_tag 'autocomplete_client', '',:style => "width:100%;","data-ajax_autocomplete_path" => client_autocomplete_path, "data-ajax_info_path" => get_info_client_path %>
		<%= link_to t('.new', :default => t("helpers.links.new")), new_client_path, :remote => true, :class => 'btn btn-primary', :style => "width:10%;"%></dd>
      </dl>
      <dl class="dl-horizontal">
	    <dt></dt>
	    <dd><div id="client_name"></div></dd>
      </dl>
	  <dl class="dl-horizontal">
	    <dt><strong><%=t '.date', :default => t("helpers.labels.date") %>:</strong></dt>
	    <dd><%= f.date_select(:date, :order => [:month, :day, :year]) %></dd>
	  </dl>
	  <dl class="dl-horizontal">
	    <dt><strong><%=t '.document_number', :default => t("helpers.labels.document_number") %>:</strong></dt>
	    <dd><%= f.text_field :document_number %></dd>
	  </dl>
	  <dl class="dl-horizontal">
	    <dt><strong><%=t '.warehouses', :default => t("helpers.labels.warehouses") %>:</strong></dt>
	    <dd><%= f.collection_select :warehouse_id, Account.where("domain = ? AND type = ?",current_user.domain,"Warehouse"), :id, :name %></dd>
	  </dl>
	  <dl class="dl-horizontal">
	    <dt><strong><%=t '.due', :default => t("helpers.labels.due") %>:</strong></dt>
	    <dd><%= f.text_field :due %></dd>
	  </dl>
	  <dl class="dl-horizontal">
	    <dt><strong><%=t '.tax', :default => t("helpers.labels.tax") %>:</strong></dt>
	    <dd><%= f.text_field :tax %> % </dd>
	  </dl>
	  <%= f.hidden_field :type, :value => @type_description %>
	  <%= f.hidden_field :document_type_id, :value => @type_id %>
	  <%= f.button t('.new', :default => t("helpers.links.new")), :class => 'btn btn-primary', :data => {:disable_with =>  t('.creating', :default => t("helpers.labels.creating"))} %>
	<% end %>
</div>

app/views/documents/_document_line.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th><%=t '.description', :default =>  t("helpers.labels.description") %></th>
      <th><%=t '.quantity', :default =>  t("helpers.labels.quantity") %></th>
      <th><%=t '.units', :default =>  t("helpers.labels.units") %></th>
      <th><%=t '.price', :default =>  t("helpers.labels.price") %></th>
      <th><%=t '.total', :default =>  t("helpers.labels.total") %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @document.document_lines.each do |document_line| %>
      <tr>
        <td><%= document_line.description %></td>
        <td><%= document_line.out_quantity %></td>
        <td><%= document_line.product.units %></td>
        <td><%= document_line.price %></td>
        <td><%= document_line.total %></td>
        <td>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),			    	
                      {:controller => :documents,
                      :action => :remove_document_line,
                      :id => document_line.id},
			    {:confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')), 
                      :method => :delete,            
                      :class => 'btn btn-mini btn-danger'} %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/documents/_documents.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th><%=t '.type', :default =>  t("helpers.labels.document_type") %></th>
      <th><%=t '.document_number', :default =>  t("helpers.labels.document_number") %></th>
      <th><%=t '.name', :default =>  t("helpers.labels.name") %></th>
      <th><%=t '.date', :default =>  t("helpers.labels.date") %></th>
      <th><%=t '.total', :default =>  t("helpers.labels.total") %></th>
      <th><%=t '.status', :default =>  t("helpers.labels.status") %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @documents.each do |document| %>
      <tr>
        <td><span class='label label-default'><%= document.type %></span></td>
        <td><%= document.document_number %></td>
        <td><%= document.account.nil? ? '' : document.account.name %></td>
        <td><%= document.date.strftime(current_user.company.date_format) %></td>
        <td><%= number_to_currency(document.total, unit: "", separator: current_user.company.separator , delimiter: current_user.company.delimiter, format: "%u %n") %></td>
        <% if document.payments_document != nil %>
         <%= display_status document.payments_document.status %>
        <% else %>
         <%= display_status document.status %>
        <% end %>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      document_path(document), :class => 'btn btn-mini btn-warning' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_document_path(document), :class => 'btn btn-mini btn-primary' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      document_path(document),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.print', :default => t("helpers.links.print")),
            documents_report_documents_path(:start_at => @start_at, :end_at => @end_at, :name => @name, :status => @status, :type => @type),
            :class => 'btn' %>

<%= will_paginate(@movies, :params => { :type => params[:type], :name => params[:name], :start_at => params[:start_at], :end_at => params[:end_at], :status => params[:status] }, renderer: BootstrapPagination::Rails ) %>

app/views/documents/_form.html.erb
<%= simple_form_for @document, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="form-actions">
    <%= label_tag(:type, (t '.type', :default =>  t("helpers.labels.document_type") ) ) %><%= f.collection_select :document_type_id, current_user.company.document_types, :id, :description %>
  </div>
  <%= f.input :document_number %>
  <%= f.input :date %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary', :data => {:disable_with =>  t('.saving', :default => t("helpers.labels.saving"))} %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                documents_path, :class => 'btn' %>
  </div>
<% end %>

app/views/documents/_provider.html.erb
<%- model_class = Provider -%>
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.js"></script>
<div class="row-fluid">
  <div class="span10">
	<div class="modal fade" id="provider-modal"></div>
    <%= form_for @document, :url => {:action => "create_document_account"}, :method => "get"  do |f| %>
      <%= render 'shared/error_messages', :object => @document %>
      <dl class="dl-horizontal">
        <dt><strong><%=t '.providers', :default =>  t("helpers.labels.providers") %></strong></dt>
        <dd><%= text_field_tag 'autocomplete_provider', '',:style => "width:100%;","data-ajax_autocomplete_path" => provider_autocomplete_path, "data-ajax_info_path" => get_info_provider_path %>
        <%= link_to t('.new', :default => t("helpers.links.new")), new_provider_path, :remote => true, :class => 'btn btn-primary', :style => "width:10%;"%></dd>
      </dl>
      <dl class="dl-horizontal">
	    <dt></dt>
	    <dd><div id="provider_name"></div></dd>
      </dl>
	  <dl class="dl-horizontal">
	    <dt><strong><%=t '.date', :default => t("helpers.labels.date") %>:</strong></dt>
	    <dd><%= f.date_select(:date, :order => [:month, :day, :year]) %></dd>
	  </dl>
	  <dl class="dl-horizontal">
	    <dt><strong><%=t '.document_number', :default => t("helpers.labels.document_number") %>:</strong></dt>
	    <dd><%= f.text_field :document_number %></dd>
	  </dl>
	  <dl class="dl-horizontal">
	    <dt><strong><%=t '.warehouses', :default => t("helpers.labels.warehouses") %>:</strong></dt>
	    <dd><%= f.collection_select :warehouse_id, Account.where("domain = ? AND type = ?",current_user.domain,"Warehouse"), :id, :name %></dd>
	  </dl>
	  <dl class="dl-horizontal">
	    <dt><strong><%=t '.due', :default => t("helpers.labels.due") %>:</strong></dt>
	    <dd><%= f.text_field :due %></dd>
	  </dl>
	  <dl class="dl-horizontal">
	    <dt><strong><%=t '.tax', :default => t("helpers.labels.tax") %>:</strong></dt>
	    <dd><%= f.text_field :tax %> % </dd>
	  </dl>
	  <%= f.hidden_field :type, :value => @type_description %>
	  <%= f.hidden_field :document_type_id, :value => @type_id %>
	  <%= f.button t('.new', :default => t("helpers.links.new")), :class => 'btn btn-primary', :data => {:disable_with =>  t('.creating', :default => t("helpers.labels.creating"))} %>
	<% end %>
</div>

app/views/documents/_warehouse.html.erb
<%- model_class = Warehouse -%>
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.js"></script>
<div class="row-fluid">
  <div class="span10">
	<div class="modal fade" id="warehouse-modal"></div>
    <%= form_for @document, :url => {:action => "create_document_account"}, :method => "get"  do |f| %>
      <%= render 'shared/error_messages', :object => @document %>
      <dl class="dl-horizontal">
        <dt><strong><%=t '.warehouses', :default =>  t("helpers.labels.warehouses") %></strong></dt>
        <dd><%= text_field_tag 'autocomplete_warehouse', '',:style => "width:100%;","data-ajax_autocomplete_path" => warehouse_autocomplete_path, "data-ajax_info_path" => get_info_warehouse_path %>
        <%= link_to t('.new', :default => t("helpers.links.new")), new_warehouse_path, :remote => true, :class => 'btn btn-primary', :style => "width:10%;"%></dd>
      </dl>
      <dl class="dl-horizontal">
	    <dt></dt>
	    <dd><div id="warehouse_name"></div></dd>
      </dl>
	  <dl class="dl-horizontal">
	    <dt><strong><%=t '.date', :default => t("helpers.labels.date") %>:</strong></dt>
	    <dd><%= f.date_select(:date, :order => [:month, :day, :year]) %></dd>
	  </dl>
	  <dl class="dl-horizontal">
	    <dt><strong><%=t '.document_number', :default => t("helpers.labels.document_number") %>:</strong></dt>
	    <dd><%= f.text_field :document_number %></dd>
	  </dl>
	  <dl class="dl-horizontal">
	    <dt><strong><%=t '.warehouses', :default => t("helpers.labels.warehouses") %>:</strong></dt>
	    <dd><%= f.collection_select :warehouse_id, Account.where("domain = ? AND type = ?",current_user.domain,"Warehouse"), :id, :name %></dd>
	  </dl>
	  <dl class="dl-horizontal">
	    <dt><strong><%=t '.due', :default => t("helpers.labels.due") %>:</strong></dt>
	    <dd><%= f.text_field :due %></dd>
	  </dl>
	  <dl class="dl-horizontal">
	    <dt><strong><%=t '.tax', :default => t("helpers.labels.tax") %>:</strong></dt>
	    <dd><%= f.text_field :tax %> % </dd>
	  </dl>
	  <%= f.hidden_field :type, :value => @type_description %>
	  <%= f.hidden_field :document_type_id, :value => @type_id %>
	  <%= f.button t('.new', :default => t("helpers.links.new")), :class => 'btn btn-primary',  :data => {:disable_with =>  t('.creating', :default => t("helpers.labels.creating"))} %>
	<% end %>
</div>

app/views/documents/index.js.erb
$("#documents").html("<%= escape_javascript(render("documents")) %>");