config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  
  resources :providers do
    get "providers_report", :on => :collection
    get "account_report", :on => :collection   
  end
  
  resources :products do
    get "product_list_report", :on => :collection
  end
  
  resources :clients do
    get "clients_report", :on => :collection
    get "account_report", :on => :collection   
  end
  
  resources :documents do
    get "documents_report", :on => :collection
    get "document_report", :on => :collection
    get "document_report2", :on => :collection
    get "document_report3", :on => :collection
    get "personalize_report", :on => :collection
  end
  
  resources :users
  resources :companies
  resources :clients
  resources :providers
  resources :warehouses
  resources :products
  resources :brands
  resources :categories
  resources :documents
  resources :document_types
  resources :document_lines
  resources :stocks
  resources :payments
  resources :payments_documents
  resources :payment_types
  
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do

    devise_for :users, :controllers => { :registrations => "registrations"}
    
    get '/:locale/documents/search' => 'documents#search', :as => :documents_search
    get '/:locale/stocks/search' => 'stocks#search', :as => :stock_search
    get '/:locale/clients/search' => 'clients#search', :as => :client_search
    get '/:locale/providers/search' => 'providers#search', :as => :provider_search
    get '/:locale/products/search' => 'products#search', :as => :products_search
    get '/:locale/payments_documents/search' => 'payments_documents#search', :as => :payments_documents_search

    get '/:locale/companies/settings' => 'companies#settings', :as => :settings
    get '/:locale/companies/edit_formats' => 'companies#edit_formats', :as => :edit_formats     
 
    get '/:locale/clients/autocomplete' => 'clients#autocomplete', :as => :client_autocomplete
    get '/:locale/clients/get_info_account' => 'clients#get_info_from_selected_account', :as => :get_info_client

    get '/:locale/providers/autocomplete' => 'providers#autocomplete', :as => :provider_autocomplete
    get '/:locale/providers/get_info_account' => 'providers#get_info_from_selected_account', :as => :get_info_provider

    get '/:locale/warehouses/autocomplete' => 'warehouses#autocomplete', :as => :warehouse_autocomplete
    get '/:locale/warehouses/get_info_account' => 'warehouses#get_info_from_selected_account', :as => :get_info_warehouse   

    delete '/:locale/documents/remove_document_line' => 'documents#remove_document_line', :as => :document_remove_document_line
    post '/:locale/documents/create_document_line' => 'documents#create_document_line', :as => :create_document_line
    get '/:locale/documents/create_document_account' => 'documents#create_document_account', :as => :create_document_account  
    get '/:locale/documents/new' => 'documents#new', :as => :new

    get '/:locale/products/autocomplete' => 'products#autocomplete', :as => :product_autocomplete
    get '/:locale/products/get_info_product' => 'products#get_info_from_selected_product', :as => :get_info_product

    get '/:locale/payments_documents/add_payments_document_id' => 'payments_documents#add_payments_document_id', :as => :add_payments_document_id  
    get '/:locale/payments_documents/remove_payments_document_id' => 'payments_documents#remove_payments_document_id', :as => :remove_payments_document_id  
    post '/:locale/payments_documents/create_payment_line' => 'payments_documents#create_payment_line', :as => :create_payment_line
#    get '/:locale/payments_documents/new' => 'payments_documents#new', :as => :new
    get '/:locale/payments_documents/new_modal' => 'payments_documents#new_modal', :as => :new_modal
    get '/:locale/payments_documents/create_payments_document_account' => 'payments_documents#create_payments_document_account', :as => :create_payments_document_account   

    get '/:locale/learn' => 'learn#index', :as => :learn_personalize_report
    get '/:locale/privacy' => 'privacy#index', :as => :privacy
    get '/:locale/terms' => 'terms#index', :as => :terms 

    patch '/upload_logo' => 'companies#upload_logo', :as => :upload_logo
    get '/delete_logo' => 'companies#delete_logo', :as => :delete_logo
    
    get '/:locale/service_payments/subscribe_month' => 'service_payments#subscribe_month', :as => :subscribe_month 
    get '/:locale/service_payments/subscribe_year' => 'service_payments#subscribe_year', :as => :subscribe_year
  end
end

app/models/company.rb
class Company < ApplicationRecord
  self.primary_key = 'id'  
  validates :name, presence: true

  PLANS = ["GRATIS","PAGO"]
  validates :plan, inclusion: PLANS
  
  has_many :users, :foreign_key => 'domain'
  has_many :products, :foreign_key => 'domain'
  has_many :brands, :foreign_key => 'domain'
  has_many :categories, :foreign_key => 'domain'
  has_many :accounts, :foreign_key => 'domain'
  has_many :document_types, :foreign_key => 'domain'
  has_many :stocks, :foreign_key => 'domain'
  has_many :documents, :foreign_key => 'domain'
  has_many :document_lines, :foreign_key => 'domain'
  has_many :payments, :foreign_key => 'domain'
  has_many :payments_documents, :foreign_key => 'domain'
  has_many :service_payments, :foreign_key => 'domain'
  has_many :payment_types, :foreign_key => 'domain'
  
  has_attached_file :logo,
#      :storage => :dropbox,
#      :dropbox_credentials => Rails.root.join("config/dropbox.yml"),
#      :dropbox_options => {
#       path: proc{|style| "#{style}/#{id}_#{logo.original_filename}"}
#      },
      styles: {
      thumb: '100x100>',
      square: '500x200>',
      medium: '300x300>'
    }, :url => '/:class/:attachment/:id/:style_:basename.:extension'

# Validate content type
  validates_attachment_content_type :logo, :content_type => /\Aimage\/.*\Z/

end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  # GET /companies
  # GET /companies.json
  before_action :authenticate_user!
  def index
#    @companies = Company.all
    @company = Company.find(current_user.company.id)

    respond_to do |format|
      format.html { redirect_to @company }
      format.json { render json: @company }
    end
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
    @company = Company.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @company }
    end
  end

  # GET /companies/new
  # GET /companies/new.json
  def new
    @company = Company.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @company }
    end
  end

  # GET /companies/1/edit
  def edit
    @company = Company.find(params[:id])
    respond_to do |format|
      format.js
      format.html
    end
  end

  # GET /companies/1/edit
  def edit_formats
    @company = Company.find(params[:id])
    respond_to do |format|
      format.js
      format.html
    end
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render json: @company, status: :created, location: @company }
      else
        format.html { render action: "new" }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /companies/1
  # PUT /companies/1.json
  def update
    @company = Company.find(params[:id])

    respond_to do |format|
      if @company.update_attributes(company_params)
        format.js do
          if params[:update_formats]
            render 'update_formats'
          else
            render 'update'
          end
        end
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { head :no_content }
      else
        format.js { render action: "edit" }
        format.html { render action: "edit" }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company = Company.find(params[:id])
    @company.destroy

    respond_to do |format|
      format.html { redirect_to companies_url }
      format.json { head :no_content }
    end
  end
  

  def upload_logo
    @company = current_user.company
    @company.logo = params[:logo]
    @logo_uploaded = @company.save
  end

  def delete_logo
    @company = current_user.company
    @company.logo = nil
    @company.save
  end

   # ############# Para Pruebas 
   #  def became_free
   #     @company = Company.find(current_user.company.id)
   #     @company.plan = "GRATIS"
   #     @company.initial_cycle = Time.new
   #     @company.final_cycle = Time.now.months_since(1)
   #     @company.counter = 0
   #     @company.limit = 3
   #     
   #     respond_to do |format|
   #        if @company.save
   #    	    format.js { @company.errors[:base] << "SE puso gratis" } 
   #        else
   #          format.js { @company.errors[:base] << "Error al actualizar plan"} 
   #        end
   #      end
   #   end
   ####################   

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:id, :name, :address, :id_number1, :id_number2, :address, :city, :state, :country, :zip_code, :telephone, :fax, :email, :web, :contact, :initial_cycle, :final_cycle, :plan, :counter, :limit, :note, :date_format, :unit, :separator, :delimiter, :id_number1_label)
    end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_company.html.erb
<dl class="dl-horizontal">
  <dt><strong><%= t '.code', :default => t("helpers.labels.code") %></strong></dt>
  <dd><%= @company.id %></dd>
</dl>
<dl class="dl-horizontal">
  <dt><strong><%= t '.name', :default => t("helpers.labels.name") %></strong></dt>
  <dd><%= @company.name %></dd>
</dl>
<dl class="dl-horizontal">
  <dt><strong><%= @company.id_number1_label %></strong></dt>
  <dd><%= @company.id_number1 %></dd>
</dl>
<dl class="dl-horizontal">
  <dt><strong><%= t '.address', :default => t("helpers.labels.address") %></strong></dt>
  <dd><%= @company.address %></dd>
</dl>
<dl class="dl-horizontal">
  <dt><strong><%= t '.city', :default => t("helpers.labels.city") %></strong></dt>
  <dd><%= @company.city %></dd>
</dl>
<dl class="dl-horizontal">
  <dt><strong><%= t '.state', :default => t("helpers.labels.state") %></strong></dt>
  <dd><%= @company.state %></dd>
</dl>
<dl class="dl-horizontal">
  <dt><strong><%= t '.country', :default => t("helpers.labels.country") %></strong></dt>
  <dd><%= @company.country %></dd>
</dl>
<dl class="dl-horizontal">
  <dt><strong><%= t '.zip_code', :default => t("helpers.labels.zip_code") %></strong></dt>
  <dd><%= @company.zip_code %></dd>
</dl>
<dl class="dl-horizontal">
  <dt><strong><%= t '.telephone', :default => t("helpers.labels.telephone") %></strong></dt>
  <dd><%= @company.telephone %></dd>
</dl>
<dl class="dl-horizontal">
  <dt><strong><%= t '.fax', :default => t("helpers.labels.fax") %></strong></dt>
  <dd><%= @company.fax %></dd>
</dl>
<dl class="dl-horizontal">
  <dt><strong><%= t '.email', :default => t("helpers.labels.email") %></strong></dt>
  <dd><%= @company.email %></dd>
</dl>
<dl class="dl-horizontal">
  <dt><strong><%= t '.web', :default => t("helpers.labels.web") %></strong></dt>
  <dd><%= @company.web %></dd>
</dl>
<dl class="dl-horizontal">
  <dt><strong><%= t '.contact', :default => t("helpers.labels.contact") %></strong></dt>
  <dd><%= @company.contact %></dd>
</dl>
<div class="form-actions">
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_company_path(@company), :class => 'btn switcher', remote: true %>
</div>

app/views/companies/_form.html.erb
<%= simple_form_for @company, :html => { :multipart => true , :class => 'form-horizontal' }, :remote => true do |f| %>
  <%= f.input :name %>
  <%= f.input :id_number1_label %>
  <%= f.input :id_number1 %>
  <%= f.input :address , input_html: { style: "width:50%;" } %>
  <%= f.input :city %>
  <%= f.input :state %>
  <%= f.input :country %>
  <%= f.input :zip_code %>
  <%= f.input :telephone %>
  <%= f.input :fax %>
  <%= f.input :email %>
  <%= f.input :web %>
  <%= f.input :contact %>

  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
  </div>
<% end %>

app/views/companies/_formats_form.html.erb
<%= simple_form_for @company, :html => { :multipart => true , :class => 'form-horizontal' }, remote: true do |f| %>
  <%= hidden_field_tag 'update_formats', '1' %>
  <%= f.input :unit %>
  <%= f.input :separator %>
  <%= f.input :delimiter %>
  <%= f.label :date_format %><span style="padding: 0 7px">&nbsp;</span><%= f.select :date_format, options_for_select([['01/01/2001', '%d/%m/%Y'], ['01-01-2001', '%d-%m-%Y'], ['01/Ene/2001', '%d/%B/%Y']],:disabled => ["Select One"]) %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
  </div>
<% end %>

app/views/companies/_service_payments.html.erb
<%- model_class = ServicePayment -%>
<div class="page-header">
  <h1><%=t '.title', :default => t("helpers.labels.service_payments") %></h1>
</div>
<div class="modal fade" id="user-modal"></div>
<table class="table table-striped">
  <thead>
    <tr>
	  <th><%= t '.code', :default => t("helpers.labels.code") %></th>  
      <th><%= t '.payment_id', :default => t("helpers.labels.payment_id") %></th>
      <th><%= t '.date', :default => t("helpers.labels.date") %></th>
      <th><%= t '.method', :default => t("helpers.labels.method") %></th>
      <th><%= t '.description', :default => t("helpers.labels.description") %></th>
      <th><%= t '.amount', :default => t("helpers.labels.amount") %></th>
      <th><%= t '.state', :default => t("helpers.labels.state") %></th>
    </tr>
  </thead>
  <tbody>
    <% current_user.company.service_payments.each do |service_payment| %>
      <tr>
        <td><%= service_payment.id %></td>
        <td><%= service_payment.payment_id %></td>
        <td><%= service_payment.created_at.strftime(@company.date_format) %></td>
        <td><%= service_payment.method %></td>
        <td><%= service_payment.description %></td>
        <td><%= number_to_currency(service_payment.amount, unit: '$', separator: @company.separator  , delimiter: @company.delimiter, format: "%u %n") %></td>
        <%= display_state service_payment.state %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/companies/_subscribe.html.erb
<script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
<script type="text/javascript" src="https://www.mercadopago.com/org-img/jsapi/mptools/buttons/render.js"></script>

<input type="hidden" id="subscribe_year" name="subscribe_year" ajax_path=<%= subscribe_year_path() %> >
<input type="hidden" id="subscribe_month" name="subscribe_month" ajax_path=<%= subscribe_month_path() %> >

<script type="text/javascript">
function execute_month_onreturn (json) {
  if (json.collection_status=='approved'){
	$.ajax({
	  url: $('#subscribe_month').attr('ajax_path'),
	  data: { },
	  async: true,
	  dataType: 'script'
	});
    alerta ('Pago de un mes acreditado');
  } else if(json.collection_status=='pending'){
    alerta ('El usuario no completó el pago');
  } else if(json.collection_status=='in_process'){
    alerta ('El pago está siendo revisado');
  } else if(json.collection_status=='rejected'){
    alerta ('El pago fué rechazado, el usuario puede intentar nuevamente el pago');
  } else if(json.collection_status==null){
    alerta ('El usuario no completó el proceso de pago de un mes, no se ha generado ningún pago');
  }
}
function execute_year_onreturn (json) {
  if (json.collection_status=='approved'){
	$.ajax({
	  url: $('#subscribe_year').attr('ajax_path'),
	  data: { },
	  async: true,
	  dataType: 'script'
	});
    alerta ('Pago de un año acreditado');
  } else if(json.collection_status=='pending'){
    alerta ('El usuario no completó el pago');
  } else if(json.collection_status=='in_process'){
    alerta ('El pago está siendo revisado');
  } else if(json.collection_status=='rejected'){
    alerta ('El pago fué rechazado, el usuario puede intentar nuevamente el pago');
  } else if(json.collection_status==null){
    alerta ('El usuario no completó el proceso de pago de un año, no se ha generado ningún pago');
  }
}
function alerta (msg) {
	$.ajax({
	  url: $('#subscribe_alert').attr('ajax_path'),
	  data: { msg : msg },
	  async: true,
	  dataType: 'script'
	});
}
</script>


<div class="span5" id="formatsPlace">
  <%= render 'subscription' %>
</div>

app/views/companies/_subscription.html.erb
<%= render 'shared/error_messages', :object => @company %>
<dl class="dl-horizontal">
  <dt><strong><%= @company.counter %> de <%= @company.limit %></strong></dt>
</dl>
<div class="progress progress-warning">
  <div class="bar" style="width: <%= 100*@company.counter/@company.limit %>%"></div>
</div>
<dl class="dl-horizontal">
  <dt><strong><%=t '.initial_cycle', :default =>  t("helpers.labels.initial_cycle") %></strong></dt>
  <dd><%=  @company.initial_cycle.strftime(@company.date_format) %></dd>
</dl>
<dl class="dl-horizontal">
  <dt><strong><%=t '.final_cycle', :default =>  t("helpers.labels.final_cycle") %></strong></dt>
  <dd><%= @company.final_cycle.strftime(@company.date_format) %></dd>
</dl>
    <dl class="dl-horizontal">
      <dt><strong><%=t '.plan', :default =>  t("helpers.labels.plan") %></strong></dt>
	  <% if @company.plan == nil || @company.plan == "GRATIS" %>
	      <dd><td><span class="label label-important">GRATIS</span> </td></dd>
	    </dl>
	    <dl class="dl-horizontal">
	        <dt><%= link_to t('.subscribe_month', :default => t("helpers.links.subscribe_month")), subscribe_month_path, :class => 'btn btn-primary' %></dt>
	         <dd><%= number_to_currency(22, unit: '$', separator: @company.separator , delimiter: @company.delimiter, format: "%u %n") %></dd> 
	      </dl>
	      <dl class="dl-horizontal">
	        <dt><%= link_to t('.subscribe_year', :default => t("helpers.links.subscribe_year")), subscribe_year_path, :class => 'btn btn-danger' %></dt>
	        <dd><%= number_to_currency(220, unit: '$', separator: @company.separator , delimiter: @company.delimiter, format: "%u %n") %></dd> 
	      </dl>
	  <% elsif @company.plan != nil && @company.plan == "PAGO" %>
	      <dd><td><span class="label label-success"> <%= @company.plan %> </span></td></dd>
	    </dl>
	  <% end %>

  <dl class="dl-horizontal">
    <%= link_to t('.edit_formats', :default => t("helpers.links.edit_formats")),
                edit_formats_path(:id => @company.id), :class => 'btn',:style => "width:90%;", remote: true   %>
  </dl>

app/views/companies/edit.js.erb
$('#companyPlace').html("<%= j (render 'form') %>");

app/views/companies/edit_formats.html.erb
<%- model_class = Company -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'formats_form' %>

app/views/companies/index.html.erb
<%- model_class = Company -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:address) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><%= link_to company.id, company_path(company) %></td>
        <td><%= company.name %></td>
        <td><%= company.address %></td>
        <td><%=l company.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_company_path(company), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      company_path(company),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_company_path,
            :class => 'btn btn-primary' %>

app/views/companies/new.html.erb
<%- model_class = Company -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/companies/settings.html.erb
<%= react_component 'DocumentTypes',
                    {
                        data: current_user.company.document_types,
                        page_header: t('.title', :default => DocumentType.model_name.human.pluralize.titleize),
                        form_data: {
                            account_types: DocumentType::ACCOUNT_TYPES,
                            stock_types: DocumentType::STOCK_TYPES,
                            select_prompt: t('.select', :default => t("helpers.links.select")),
                        }
                    } %>

<%= react_component 'PaymentTypes',
                    {
                        data: current_user.company.payment_types,
                        page_header: t('.title', :default => PaymentType.model_name.human.pluralize.titleize),
                        form_data: {
                        }
                    } %>

<%= react_component 'Warehouses',
                    {
                        data: Account.where("domain = ? AND type = ?", current_user.domain, "Warehouse"),
                        page_header: t('.title', :default => Warehouse.model_name.human.pluralize.titleize),
                        form_data: {
                        }
                    } %>

<%= react_component 'Categories',
                    {
                        data: current_user.company.categories,
                        page_header: t('.title', :default => Category.model_name.human.pluralize.titleize),
                        form_data: {
                        }
                    } %>

<%= react_component 'Brands',
                    {
                        data: current_user.company.brands,
                        page_header: t('.title', :default => Brand.model_name.human.pluralize.titleize),
                        form_data: {
                        }
                    } %>

app/views/companies/show.html.erb
<%- model_class = Company -%>
<script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
<script type="text/javascript" src="https://www.mercadopago.com/org-img/jsapi/mptools/buttons/render.js"></script>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>
<div class="row-fluid">
  <div class="span7">
    <div id="companyPlace">
      <%= render :partial => 'company' %>
    </div>
  </div>
  <div id="subscribe">
    <%= render :partial => 'subscribe' %>
  </div>
</div>

<%= render :partial => 'users' %>
<%= render :partial => 'service_payments' %>

app/views/companies/update.js.erb
$('#companyPlace').html("<%= j (render 'company') %>");

app/views/companies/update_formats.js.erb
$('#formatsPlace').html("<%= j (render 'subscription') %>");