config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  
  resources :providers do
    get "providers_report", :on => :collection
    get "account_report", :on => :collection   
  end
  
  resources :products do
    get "product_list_report", :on => :collection
  end
  
  resources :clients do
    get "clients_report", :on => :collection
    get "account_report", :on => :collection   
  end
  
  resources :documents do
    get "documents_report", :on => :collection
    get "document_report", :on => :collection
    get "document_report2", :on => :collection
    get "document_report3", :on => :collection
    get "personalize_report", :on => :collection
  end
  
  resources :users
  resources :companies
  resources :clients
  resources :providers
  resources :warehouses
  resources :products
  resources :brands
  resources :categories
  resources :documents
  resources :document_types
  resources :document_lines
  resources :stocks
  resources :payments
  resources :payments_documents
  resources :payment_types
  
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do

    devise_for :users, :controllers => { :registrations => "registrations"}
    
    get '/:locale/documents/search' => 'documents#search', :as => :documents_search
    get '/:locale/stocks/search' => 'stocks#search', :as => :stock_search
    get '/:locale/clients/search' => 'clients#search', :as => :client_search
    get '/:locale/providers/search' => 'providers#search', :as => :provider_search
    get '/:locale/products/search' => 'products#search', :as => :products_search
    get '/:locale/payments_documents/search' => 'payments_documents#search', :as => :payments_documents_search

    get '/:locale/companies/settings' => 'companies#settings', :as => :settings
    get '/:locale/companies/edit_formats' => 'companies#edit_formats', :as => :edit_formats     
 
    get '/:locale/clients/autocomplete' => 'clients#autocomplete', :as => :client_autocomplete
    get '/:locale/clients/get_info_account' => 'clients#get_info_from_selected_account', :as => :get_info_client

    get '/:locale/providers/autocomplete' => 'providers#autocomplete', :as => :provider_autocomplete
    get '/:locale/providers/get_info_account' => 'providers#get_info_from_selected_account', :as => :get_info_provider

    get '/:locale/warehouses/autocomplete' => 'warehouses#autocomplete', :as => :warehouse_autocomplete
    get '/:locale/warehouses/get_info_account' => 'warehouses#get_info_from_selected_account', :as => :get_info_warehouse   

    delete '/:locale/documents/remove_document_line' => 'documents#remove_document_line', :as => :document_remove_document_line
    post '/:locale/documents/create_document_line' => 'documents#create_document_line', :as => :create_document_line
    get '/:locale/documents/create_document_account' => 'documents#create_document_account', :as => :create_document_account  
    get '/:locale/documents/new' => 'documents#new', :as => :new

    get '/:locale/products/autocomplete' => 'products#autocomplete', :as => :product_autocomplete
    get '/:locale/products/get_info_product' => 'products#get_info_from_selected_product', :as => :get_info_product

    get '/:locale/payments_documents/add_payments_document_id' => 'payments_documents#add_payments_document_id', :as => :add_payments_document_id  
    get '/:locale/payments_documents/remove_payments_document_id' => 'payments_documents#remove_payments_document_id', :as => :remove_payments_document_id  
    post '/:locale/payments_documents/create_payment_line' => 'payments_documents#create_payment_line', :as => :create_payment_line
#    get '/:locale/payments_documents/new' => 'payments_documents#new', :as => :new
    get '/:locale/payments_documents/new_modal' => 'payments_documents#new_modal', :as => :new_modal
    get '/:locale/payments_documents/create_payments_document_account' => 'payments_documents#create_payments_document_account', :as => :create_payments_document_account   

    get '/:locale/learn' => 'learn#index', :as => :learn_personalize_report
    get '/:locale/privacy' => 'privacy#index', :as => :privacy
    get '/:locale/terms' => 'terms#index', :as => :terms 

    patch '/upload_logo' => 'companies#upload_logo', :as => :upload_logo
    get '/delete_logo' => 'companies#delete_logo', :as => :delete_logo
    
    get '/:locale/service_payments/subscribe_month' => 'service_payments#subscribe_month', :as => :subscribe_month 
    get '/:locale/service_payments/subscribe_year' => 'service_payments#subscribe_year', :as => :subscribe_year
  end
end

app/models/payment.rb
class Payment < ApplicationRecord
  self.primary_key = 'id'  
  belongs_to :company, :foreign_key => 'domain'
  belongs_to :payment_type, :foreign_key => 'payment_type_id'
  belongs_to :payments_document

#  TYPES = ["CHEQUE","DEPOSITO","EFECTIVO","RETENCION","TRANSFERENCIA"]
#  validates :payment_type, inclusion: TYPES

  before_create :sum_payments
  before_destroy :substract_payments

  protected

  def sum_payments
    payments_document.paid = payments_document.paid + amount.round(2)
    payments_document.paid_left = payments_document.total - payments_document.paid
    if (payments_document.paid > 0 && payments_document.paid_left > 0) 
      payments_document.status = "PARTIAL_PAID"
    elsif (payments_document.paid > 0 && payments_document.paid_left == 0) 
      payments_document.status = "PAID"
    elsif payments_document.paid == 0 
      payments_document.status = "NOT_PAID"
    end		
    payments_document.save
  end

  def substract_payments
    payments_document.paid = payments_document.paid - amount.round(2)
    payments_document.paid_left = payments_document.paid_left + amount
    if (payments_document.paid > 0 && payments_document.paid_left > 0) 
      payments_document.status = "PARTIAL_PAID"
    elsif (payments_document.paid > 0 && payments_document.paid_left == 0) 
      payments_document.status = "PAID"
    elsif payments_document.paid == 0 
      payments_document.status = "NOT_PAID"
    end
    payments_document.save
  end

end

app/models/payment_type.rb
class PaymentType < ApplicationRecord
  self.primary_key = 'id'  
  validates :code, presence: true
  validates :description, presence: true
  
  belongs_to :company, :foreign_key => 'domain'
  has_many :payments, :dependent => :restrict_with_error

end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  # GET /payments
  # GET /payments.json
  before_action :authenticate_user!
  def index
    @payments = current_user.company.payments.paginate(:page => params[:page], :per_page => 10).order('created_at ASC')

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @payments }
    end
  end

  # GET /payments/1
  # GET /payments/1.json
  def show
    @payment = Payment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @payment }
    end
  end

  # GET /payments/new
  # GET /payments/new.json
  def new
    @payment = Payment.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @payment }
    end
  end

  # GET /payments/1/edit
  def edit
    @payment = Payment.find(params[:id])
  end

  # POST /payments
  # POST /payments.json
  def create
    params[:payment][:version] = ENV["VERSION"]
    params[:payment][:domain] = current_user.domain
    params[:payment][:username] = current_user.username
    @payment = Payment.new(payment_params)

    respond_to do |format|
      if @payment.save
        format.html { redirect_to @payment, notice: 'Payment was successfully created.' }
        format.json { render json: @payment, status: :created, location: @payment }
      else
        format.html { render action: "new" }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /payments/1
  # PUT /payments/1.json
  def update
    params[:payment][:version] = ENV["VERSION"]
    params[:payment][:username] = current_user.username
    @payment = Payment.find(params[:id])

    respond_to do |format|
      if @payment.update_attributes(payment_params)
        format.html { redirect_to @payment, notice: 'Payment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payments/1
  # DELETE /payments/1.json
  def destroy
    @payment = Payment.find(params[:id])
    @payments_document = PaymentsDocument.find(@payment.payments_document.id)
    @payment.destroy

    respond_to do |format|
      format.html { redirect_to @payments_document, notice: 'Payment was successfully deleted.'  }
      format.json { head :no_content }
    end
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_payment
      @payment = Payment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def payment_params
      params.require(:payment).permit(:amount, :date, :domain, :id, :notes, :payment_type_id, :username, :version, :payments_document_id)
    end
end

app/views/payments/_form.html.erb
<%= simple_form_for @payment, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :version %>
  <%= f.input :domain %>
  <%= f.input :username %>
  <%= f.input :payment_type %>
  <%= f.input :notes %>
  <%= f.input :date %>
  <%= f.input :amount %>
  <%= f.input :header_id %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                payments_path, :class => 'btn' %>
  </div>
<% end %>

app/views/payments/edit.html.erb
<%- model_class = Payment -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/payments/index.html.erb
<%- model_class = Payment -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:payment_type) %></th>
      <th><%= model_class.human_attribute_name(:notes) %></th>
      <th><%= model_class.human_attribute_name(:date) %></th>
      <th><%= model_class.human_attribute_name(:amount) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @payments.each do |payment| %>
      <tr>
        <td><%= link_to payment.payment_type, payment_path(payment) %></td>
        <td><%= payment.notes %></td>
        <td><%= payment.date %></td>
        <td><%= payment.amount %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_payment_path(payment), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      payment_path(payment),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_payment_path,
            :class => 'btn btn-primary' %>

<%= will_paginate(@movies, renderer: BootstrapPagination::Rails ) %>

app/views/payments/new.html.erb
<%- model_class = Payment -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/payments/show.html.erb
<%- model_class = Payment -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:version) %>:</strong></dt>
  <dd><%= @payment.version %></dd>
  <dt><strong><%= model_class.human_attribute_name(:domain) %>:</strong></dt>
  <dd><%= @payment.domain %></dd>
  <dt><strong><%= model_class.human_attribute_name(:username) %>:</strong></dt>
  <dd><%= @payment.username %></dd>
  <dt><strong><%= model_class.human_attribute_name(:payment_type) %>:</strong></dt>
  <dd><%= @payment.payment_type %></dd>
  <dt><strong><%= model_class.human_attribute_name(:notes) %>:</strong></dt>
  <dd><%= @payment.notes %></dd>
  <dt><strong><%= model_class.human_attribute_name(:date) %>:</strong></dt>
  <dd><%= @payment.date %></dd>
  <dt><strong><%= model_class.human_attribute_name(:amount) %>:</strong></dt>
  <dd><%= @payment.amount %></dd>
  <dt><strong><%= model_class.human_attribute_name(:header_id) %>:</strong></dt>
  <dd><%= @payment.header_id %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              payments_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_payment_path(@payment), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              payment_path(@payment),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>